### ISSUE TITLE
Plugin won't load

### ISSUE THREAD

**Issue by michaelschapira** [pa-decarvalho/mkdocs-asciinema-player#16]
Good morning, 

I am trying to use your plugin (thanks !), but when I start the `mkdocs server` I get a python error :

I wonder if it's related to my version of python. 

```
FileNotFoundError: [Errno 2] No such file or directory: \ 
'<redacted>/env/lib/python3.9/site-packages/mkdocs_asciinema_player/assets/icons'
```

I did install the python package successfully:

```
pip freeze | grep asciinema                          
mkdocs-asciinema-player==0.8.1
```

**Comment by pa-decarvalho** [comment]
Hi @michaelschapira,

Thank you for reporting this issue !

I just noticed that I hadn't included the "icons" resources in the `MANIFEST.in` file. I will create a quick fix for this.

I was considering removing these icons and using a CSS library to replace them, but I haven't taken the time to do it yet ([Improved blue theme buttons](https://github.com/pa-decarvalho/mkdocs-asciinema-player/issues/15).

Thank you for using this project and contributing to its improvement :)

**Comment by pa-decarvalho** [comment]
@michaelschapira You can use `mkdocs-asciinema-player==0.8.2`. I tested it on a private project and it works.

Feel free to reopen this issue if you have any troubles.

**Comment by michaelschapira** [comment]
Thank you so much for the fast response. 
It's working fine now.
