### ISSUE TITLE
Allow to use Mkdocs `site_url` with default `null` value

### ISSUE THREAD

**Issue by llaville** [pa-decarvalho/mkdocs-asciinema-player#21]
Hello,

I've recently discover your project and I like it. But after some tries to make it running I found a nasty bug !

Here is my context.

- I want to build a site with [Material for MkDocs](https://github.com/squidfunk/mkdocs-material) 

- My `mkdocs.yml` config file identify my online website (I've replaced final target by `my_project` to be simple)

```yaml
---
site_url: https://llaville.github.io/my_project
```

- I build the site with following command : 

```shell
mkdocs build --verbose --no-directory-urls --clean
```

- I test it on my local vhost `http://my_project.dvl.to/` and when I play the `asciinema` embedded player I got this output 

![my_project dvl to](https://github.com/user-attachments/assets/2d53ea44-4dce-48c9-905e-538b6aed917c)

After searching origin, I found that code included in `index.html` contains 

```html
<script>
    window.addEventListener("load", function(event) {
        AsciinemaPlayer.create("/my_project/assets/asciinema/demo.cast", document.getElementById("asciinema-player-0"), {
            cols: 120,
            rows: 24,
            autoPlay: false,
            preload: false,
            loop: false,
            startAt: "0:00",
            speed: 1.0,
            theme: "asciinema",
            fit: "width",
            controls: "auto",
            pauseOnMarkers: true,
            terminalFontSize: "small",
            terminalFontFamily: "",
            terminalLineHeight: 1.33333333,
        });
    });
</script>
```

`file_path` (here `"/my_project/assets/asciinema/demo.cast"`) is wrong 

- See [asciinema-player.html](https://github.com/pa-decarvalho/mkdocs-asciinema-player/blob/0.10.0/src/mkdocs_asciinema_player/templates/asciinema-player.html#L8) template
- And [Code](https://github.com/pa-decarvalho/mkdocs-asciinema-player/blob/0.10.0/src/mkdocs_asciinema_player/plugin.py#L146) that populate data.

Last but not least : If I want to remove the `site_url` as allowed by [default Mkdocs configuration](https://www.mkdocs.org/user-guide/configuration/#site_url), and try to rebuild the doc site (always with command ` mkdocs build --verbose --no-directory-urls --clean
`) I got this issue.

```text
ERROR   -  Error reading page 'README.md': can't concat str to bytes
Traceback (most recent call last):
  File "/home/llaville/.local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/home/llaville/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/llaville/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/llaville/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/llaville/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/llaville/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/llaville/.local/lib/python3.10/site-packages/mkdocs/__main__.py", line 284, in build_command
    build.build(cfg, dirty=not clean)
  File "/home/llaville/.local/lib/python3.10/site-packages/mkdocs/commands/build.py", line 310, in build
    _populate_page(file.page, config, files, dirty)
  File "/home/llaville/.local/lib/python3.10/site-packages/mkdocs/commands/build.py", line 163, in _populate_page
    page.markdown = config.plugins.on_page_markdown(
  File "/home/llaville/.local/lib/python3.10/site-packages/mkdocs/plugins.py", line 635, in on_page_markdown
    return self.run_event('page_markdown', markdown, page=page, config=config, files=files)
  File "/home/llaville/.local/lib/python3.10/site-packages/mkdocs/plugins.py", line 566, in run_event
    result = method(item, **kwargs)
  File "/home/llaville/.local/lib/python3.10/site-packages/mkdocs_asciinema_player/plugin.py", line 169, in on_page_markdown
    return re.sub(
  File "/usr/lib/python3.10/re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/home/llaville/.local/lib/python3.10/site-packages/mkdocs_asciinema_player/plugin.py", line 146, in replace_asciinema_player_match
    parsed_json["file_path"] = urlparse(self.mkdocs_config["site_url"]).path + parsed_json["file"]
TypeError: can't concat str to bytes
```

**Workaround** (when `site_url` is NULL) is to edit the `index.html` file and replace current line 

```
        AsciinemaPlayer.create("/my_project/assets/asciinema/demo.cast", document.getElementById("asciinema-player-0"), {
```

By 

```
        AsciinemaPlayer.create("/assets/asciinema/demo.cast", document.getElementById("asciinema-player-0"), {
```

And I can play asciinema cast as expected 

![my_project dvl to__OK](https://github.com/user-attachments/assets/79907231-9d25-438d-bdd1-a44f3abf1d8b)

**Comment by pa-decarvalho** [comment]
Hi @llaville,

Thank you for reporting this issue!

I understand you want to remove the `site_url` variable for it to work, but I'm not sure it will work as intended if you try to push to GitHub or GitLab Pages.

I reproduced the bug by removing the `site_url`, and I can try to fix that, but it generates new problems. For example, on GitHub Pages, it will work on the home page because from the root `/`, it will find the `assets/path_to_your_resource`. However, if you use the plugin on another page, it will break, or you will have to manually set the path (for example, on the page `/page`, it will not find `assets/path_to_your_resource`, and you will have to set it to `../assets/path_to_your_resource`).

In this repo, you can see the `site_url` to `https://pa-decarvalho.github.io/mkdocs-asciinema-player/` (the URL of the GitHub page), and it works locally and remotely using the command `mkdocs serve` to test it.

How do you test your build locally ? Have you tried using the command `mkdocs serve` ?

I just want to understand the problem before making changes.

By the way thank you for using this project and contributing to its improvement :)

**Comment by llaville** [comment]
Ok with `mkdocs serve` it works locally, but there is an issue with `site_url` that can be NULL by MkDocs specification.

**Comment by pa-decarvalho** [comment]
Hi @llaville, I change some code to allow to use site_url with the default None value.

Feel free to reopen this issue if you have any problems.

**Comment by llaville** [comment]
Hello @pa-decarvalho,

I've a bit busy these last 2 days, but I've just tested your new version and I like it. 

Especially because it works fine when `site_url` is not defined in my `mkdocs.yml` config file and on my local vhost (while it was not the case with v.0.10.0) 

Now I can either test it both locally on my vhost and with command `mkdocs serve` and result are same.

Thanks a lot !

**Comment by llaville** [comment]
I may also test it with `mkdocs serve -f mkdocs.local.yml` with `mkdocs.local.yml` is a copy of online version `mkdocs.yml` for GH-Pages (without site_url defined)

That's help a lot. Thanks again
