### ISSUE TITLE
Create theme without terminal (default asciinema-player look)

### ISSUE THREAD

**Issue by pa-decarvalho** [pa-decarvalho/mkdocs-asciinema-player#26]
Find a name for it

**Comment by pa-decarvalho** [comment]
Hey @hany,

Yes, I agree that `none` would be a good name for this theme.

Regarding your comment about the terminal window taking up too much space, feel free to open a separate issue about this so we can discuss possible solutions for better space management if you need :)

Have a good day !

**Comment by pa-decarvalho** [comment]
@hany 

The new theme `none` is now available in version `0.12.0`. You can see an example of this theme in action in the documentation: [None Theme Example](https://pa-decarvalho.github.io/mkdocs-asciinema-player/themes/#none-theme). 

If you encounter any issues, please feel free to create a new issue.

Have a good day.

**Comment by hany** [comment]
Hey @pa-decarvalho thanks so much for the quick reply!

I just upgraded to `0.12.0` to test out the `none` theme, and am running into issues:

```
  File "/Users/hany/.pyenv/versions/3.12.2/envs/sidepro-docs/lib/python3.12/site-packages/mkdocs_asciinema_player/templates/asciinema-player.html", line 6, in top-level template code
    {% include "themes/none.html" %}
^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hany/.pyenv/versions/3.12.2/envs/sidepro-docs/lib/python3.12/site-packages/jinja2/loaders.py", line 347, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: themes/none.html
```

It seems as though the `themes/none.html` file is not present in this packaged version. I can see in `templates/asciinema-player.html` that the template now supports the `none` theme:

```
{% if mkap_theme == "night" %}
    {% include "themes/night.html" %}
{% elif mkap_theme == "blue" %}
    {% include "themes/blue.html" %}
{% elif mkap_theme == "none" %}
    {% include "themes/none.html" %}
{% endif %}
```

However in the `themes` dir, `none.html` is missing:

```console
$ ls /Users/hany/.pyenv/versions/3.12.2/envs/sidepro-docs/lib/python3.12/site-packages/mkdocs_asciinema_player/templates/themes/
blue.html	night.html
```

**Comment by pa-decarvalho** [comment]
@hany 

Yes it's my bad. I'm currently migrating the project to poetry to avoid this kind of problems. I forgot to include the file to MANIFEST.in.

I'm currently working on a other PR to refactor this.

**Comment by pa-decarvalho** [comment]
Hello again @hany, i just release `0.13.0` and test it and i can load the `none` theme.

Tell me if you encounter any new issues.

**Comment by hany** [comment]
Success! Thank you so much @pa-decarvalho! It works well!
